from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet


def create_pdf(
    result,
    filename="market_report.pdf"
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # ==================================================
    # COVER PAGE
    # ==================================================

    content.append(
        Paragraph(
            "Autonomous Market Intelligence Report",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 30))

    content.append(
        Paragraph(
            f"<b>Industry:</b> {result['industry']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Goal:</b> {result['goal']}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 40))

    content.append(
        Paragraph(
            "Generated by LangGraph Multi-Agent System",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 40))
  
    # ==================================================
    # EXECUTIVE SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            f"""
            This report analyzes the <b>{result['industry']}</b>
            industry and provides strategic recommendations
            to achieve the goal:
            <b>{result['goal']}</b>.
            """,
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Key Findings",
            styles["Heading2"]
        )
    )

    for item in result["market_report"]["trends"][:3]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(PageBreak())

    # ==================================================
    # MARKET REPORT
    # ==================================================

    content.append(
        Paragraph(
            "Market Analysis",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            "Key Trends",
            styles["Heading2"]
        )
    )

    for item in result["market_report"]["trends"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Opportunities",
            styles["Heading2"]
        )
    )

    for item in result["market_report"]["opportunities"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Risks",
            styles["Heading2"]
        )
    )

    for item in result["market_report"]["risks"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(PageBreak())

       # ==================================================
    # TREND REPORT
    # ==================================================

    content.append(
        Paragraph(
            "Industry Trend Analysis",
            styles["Heading1"]
        )
    )

    trend_text = result["trend_report"]

    trend_text = trend_text.replace(
        "**",
        ""
    )

    trend_text = trend_text.replace(
        "1.",
        "<br/><br/><b>Trend 1:</b>"
    )

    trend_text = trend_text.replace(
        "2.",
        "<br/><br/><b>Trend 2:</b>"
    )

    trend_text = trend_text.replace(
        "3.",
        "<br/><br/><b>Trend 3:</b>"
    )

    trend_text = trend_text.replace(
        "4.",
        "<br/><br/><b>Trend 4:</b>"
    )

    trend_text = trend_text.replace(
        "5.",
        "<br/><br/><b>Trend 5:</b>"
    )

    content.append(
        Paragraph(
            trend_text,
            styles["BodyText"]
        )
    )

    content.append(PageBreak())

    # ==================================================
    # COMPETITOR REPORT
    # ==================================================

    content.append(
        Paragraph(
            "Competitor Analysis",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            "Major Competitors",
            styles["Heading2"]
        )
    )

    for item in result["competitor_report"]["competitors"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Strengths",
            styles["Heading2"]
        )
    )

    for item in result["competitor_report"]["strengths"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Weaknesses",
            styles["Heading2"]
        )
    )

    for item in result["competitor_report"]["weaknesses"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    if "pricing_insights" in result["competitor_report"]:

        content.append(Spacer(1, 10))

        content.append(
            Paragraph(
                "Pricing Insights",
                styles["Heading2"]
            )
        )

        for item in result["competitor_report"]["pricing_insights"]:

            content.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )

    content.append(PageBreak())

    # ==================================================
    # STRATEGY
    # ==================================================

    content.append(
        Paragraph(
            "Strategic Recommendations",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            "Target Audience",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            result["strategy"]["target_audience"],
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Positioning",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            result["strategy"]["positioning"],
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Marketing Channels",
            styles["Heading2"]
        )
    )

    for item in result["strategy"]["marketing_channels"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading2"]
        )
    )

    for item in result["strategy"]["recommendations"]:

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    content.append(PageBreak())

    # ==================================================
    # WORKFLOW SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "Workflow Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            """
            Market Agent
            <br/><br/>
            ↓
            <br/><br/>
            Competitor Agent + Trend Agent
            <br/><br/>
            ↓
            <br/><br/>
            Strategy Agent
            <br/><br/>
            ↓
            <br/><br/>
            Human Approval
            <br/><br/>
            ↓
            <br/><br/>
            Content Agent
            """,
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 30))

    # ==================================================
    # SYSTEM INFORMATION
    # ==================================================

    content.append(
        Paragraph(
            "System Information",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            "Framework: LangGraph",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            "Memory: MemorySaver",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            "Human In The Loop: Enabled",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            "Parallel Execution: Enabled",
            styles["BodyText"]
        )
    )

    doc.build(content)

    return filename